<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Show extends \App\Entity\Show implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Show' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Show' . "\0" . 'slug', '' . "\0" . 'App\\Entity\\Show' . "\0" . 'title', '' . "\0" . 'App\\Entity\\Show' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Show' . "\0" . 'poster_url', '' . "\0" . 'App\\Entity\\Show' . "\0" . 'location', '' . "\0" . 'App\\Entity\\Show' . "\0" . 'bookable', '' . "\0" . 'App\\Entity\\Show' . "\0" . 'price', '' . "\0" . 'App\\Entity\\Show' . "\0" . 'representations', '' . "\0" . 'App\\Entity\\Show' . "\0" . 'artistTypes', '' . "\0" . 'App\\Entity\\Show' . "\0" . 'comments'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Show' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Show' . "\0" . 'slug', '' . "\0" . 'App\\Entity\\Show' . "\0" . 'title', '' . "\0" . 'App\\Entity\\Show' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Show' . "\0" . 'poster_url', '' . "\0" . 'App\\Entity\\Show' . "\0" . 'location', '' . "\0" . 'App\\Entity\\Show' . "\0" . 'bookable', '' . "\0" . 'App\\Entity\\Show' . "\0" . 'price', '' . "\0" . 'App\\Entity\\Show' . "\0" . 'representations', '' . "\0" . 'App\\Entity\\Show' . "\0" . 'artistTypes', '' . "\0" . 'App\\Entity\\Show' . "\0" . 'comments'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Show $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', []);

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlug(string $slug): \App\Entity\Show
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlug', [$slug]);

        return parent::setSlug($slug);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle(string $title): \App\Entity\Show
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(?string $description): \App\Entity\Show
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getPosterUrl(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPosterUrl', []);

        return parent::getPosterUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setPosterUrl(?string $poster_url): \App\Entity\Show
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPosterUrl', [$poster_url]);

        return parent::setPosterUrl($poster_url);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocation(): ?\App\Entity\Location
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocation', []);

        return parent::getLocation();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocation(?\App\Entity\Location $location): \App\Entity\Show
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocation', [$location]);

        return parent::setLocation($location);
    }

    /**
     * {@inheritDoc}
     */
    public function getBookable(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBookable', []);

        return parent::getBookable();
    }

    /**
     * {@inheritDoc}
     */
    public function setBookable(bool $bookable): \App\Entity\Show
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBookable', [$bookable]);

        return parent::setBookable($bookable);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', []);

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice(?string $price): \App\Entity\Show
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', [$price]);

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getRepresentations(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRepresentations', []);

        return parent::getRepresentations();
    }

    /**
     * {@inheritDoc}
     */
    public function addRepresentation(\App\Entity\Representation $representation): \App\Entity\Show
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRepresentation', [$representation]);

        return parent::addRepresentation($representation);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRepresentation(\App\Entity\Representation $representation): \App\Entity\Show
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRepresentation', [$representation]);

        return parent::removeRepresentation($representation);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtistTypes(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtistTypes', []);

        return parent::getArtistTypes();
    }

    /**
     * {@inheritDoc}
     */
    public function addArtistType(\App\Entity\ArtistType $artistType): \App\Entity\Show
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addArtistType', [$artistType]);

        return parent::addArtistType($artistType);
    }

    /**
     * {@inheritDoc}
     */
    public function removeArtistType(\App\Entity\ArtistType $artistType): \App\Entity\Show
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeArtistType', [$artistType]);

        return parent::removeArtistType($artistType);
    }

    /**
     * {@inheritDoc}
     */
    public function getComments(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComments', []);

        return parent::getComments();
    }

    /**
     * {@inheritDoc}
     */
    public function addComment(\App\Entity\Comment $comment): \App\Entity\Show
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addComment', [$comment]);

        return parent::addComment($comment);
    }

    /**
     * {@inheritDoc}
     */
    public function removeComment(\App\Entity\Comment $comment): \App\Entity\Show
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeComment', [$comment]);

        return parent::removeComment($comment);
    }

}
