<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWcj9X00\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWcj9X00/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWcj9X00.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWcj9X00\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWcj9X00\App_KernelDevDebugContainer([
    'container.build_hash' => 'Wcj9X00',
    'container.build_id' => '8b5480ac',
    'container.build_time' => 1591102967,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWcj9X00');
