<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGPMs6pm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGPMs6pm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGPMs6pm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGPMs6pm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGPMs6pm\App_KernelDevDebugContainer([
    'container.build_hash' => 'GPMs6pm',
    'container.build_id' => 'e4c3a072',
    'container.build_time' => 1592842192,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGPMs6pm');
