<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6fr3xbw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6fr3xbw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6fr3xbw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6fr3xbw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6fr3xbw\App_KernelDevDebugContainer([
    'container.build_hash' => '6fr3xbw',
    'container.build_id' => 'f7fdd89c',
    'container.build_time' => 1590942617,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6fr3xbw');
